/**
 * AUTO-GENERATED by scripts/lung_template_match.py — do not edit by hand.
 */

export const lungHealthCutawayMeta = {
	viewBox: '0 0 1024 953',
	width: 1024,
	height: 953,
	sourceImage: '/figures/lung-health/cutaway-neutral.png',
	entryAnchor: { x: 512, y: 48 },
	outdoorPortalAnchor: { x: 29, y: 49 },
	transitionPortalScale: 0.3,
	outlineStrokePx: 22,
	detectionMethod: 'opencv-template-match',
	tier1MeanMatchScore: 0.8966,
} as const;

export const lungHealthLayerBBoxes = {
	"neutrophils": {
		"x": 531,
		"y": 297,
		"width": 119,
		"height": 601,
		"pixelCount": 1586,
		"components": 2,
		"tier": 1,
		"cx": 597.9,
		"cy": 537.1,
		"method": "opencv-template-match",
		"bestScore": 0.8234,
		"matches": [
			{
				"cx": 545.0,
				"cy": 884.0,
				"score": 0.823,
				"scale": 0.94,
				"mode": "gray"
			},
			{
				"cx": 632.5,
				"cy": 314.5,
				"score": 0.588,
				"scale": 1.18,
				"mode": "purple"
			}
		]
	},
	"alveolar-macrophages": {
		"x": 469,
		"y": 849,
		"width": 162,
		"height": 77,
		"pixelCount": 3308,
		"components": 2,
		"tier": 1,
		"cx": 549.5,
		"cy": 887.4,
		"method": "opencv-template-match",
		"bestScore": 0.9247,
		"matches": [
			{
				"cx": 607.5,
				"cy": 871.0,
				"score": 0.925,
				"scale": 1.02,
				"mode": "green"
			},
			{
				"cx": 492.5,
				"cy": 904.0,
				"score": 0.908,
				"scale": 1.02,
				"mode": "green"
			}
		]
	},
	"dendritic-cells": {
		"x": 429,
		"y": 298,
		"width": 317,
		"height": 583,
		"pixelCount": 3013,
		"components": 2,
		"tier": 1,
		"cx": 614.0,
		"cy": 530.8,
		"method": "opencv-template-match",
		"bestScore": 0.9019,
		"matches": [
			{
				"cx": 456.0,
				"cy": 853.0,
				"score": 0.902,
				"scale": 1.06,
				"mode": "gray"
			},
			{
				"cx": 711.5,
				"cy": 334.0,
				"score": 0.713,
				"scale": 1.36,
				"mode": "purple"
			}
		]
	},
	"infection-antiviral-pathway": {
		"x": 611,
		"y": 84,
		"width": 85,
		"height": 52,
		"pixelCount": 1260,
		"components": 2,
		"tier": 1,
		"cx": 654.5,
		"cy": 109.5,
		"method": "opencv-template-match",
		"bestScore": 0.9362,
		"matches": [
			{
				"cx": 676.0,
				"cy": 116.5,
				"score": 0.936,
				"scale": 0.88,
				"mode": "gray"
			},
			{
				"cx": 630.0,
				"cy": 102.0,
				"score": 0.933,
				"scale": 0.82,
				"mode": "gray"
			}
		]
	},
	"antiviral-immune-mediators": {
		"x": 746,
		"y": 106,
		"width": 144,
		"height": 33,
		"pixelCount": 294,
		"components": 4,
		"tier": 2,
		"cx": 817.5,
		"cy": 121.8,
		"method": "opencv-template-match",
		"bestScore": 0.931,
		"matches": [
			{
				"cx": 757.0,
				"cy": 124.5,
				"score": 0.931,
				"scale": 1.0,
				"mode": "gray",
				"part": "dots"
			},
			{
				"cx": 861.0,
				"cy": 114.0,
				"score": 0.894,
				"scale": 0.85,
				"mode": "gray",
				"part": "antibody"
			},
			{
				"cx": 883.5,
				"cy": 129.0,
				"score": 0.843,
				"scale": 0.75,
				"mode": "gray",
				"part": "antibody"
			},
			{
				"cx": 821.0,
				"cy": 133.5,
				"score": 0.782,
				"scale": 0.6,
				"mode": "gray",
				"part": "antibody"
			}
		]
	},
	"inflammatory-signaling": {
		"x": 535,
		"y": 297,
		"width": 370,
		"height": 518,
		"pixelCount": 528,
		"components": 2,
		"tier": 2,
		"cx": 746.9,
		"cy": 511.1,
		"method": "opencv-template-match",
		"bestScore": 0.7684,
		"matches": [
			{
				"cx": 557.5,
				"cy": 804.0,
				"score": 0.768,
				"scale": 0.9,
				"mode": "gray"
			},
			{
				"cx": 877.5,
				"cy": 311.0,
				"score": 0.666,
				"scale": 1.1,
				"mode": "gray"
			}
		]
	},
	"trachea-conducting-airway": {
		"x": 340,
		"y": 20,
		"width": 72,
		"height": 102,
		"pixelCount": 5530,
		"components": 1,
		"tier": 2,
		"cx": 376.8,
		"cy": 67.3,
		"method": "opencv-template-match",
		"bestScore": 0.4657,
		"matches": [
			{
				"cx": 376.0,
				"cy": 71.0,
				"score": 0.466,
				"scale": 1.75,
				"mode": "gray"
			}
		]
	},
	"airway-epithelium": {
		"x": 622,
		"y": 166,
		"width": 176,
		"height": 103,
		"pixelCount": 17246,
		"components": 2,
		"tier": 2,
		"cx": 709.4,
		"cy": 217.0,
		"method": "opencv-template-match",
		"bestScore": 0.3812,
		"matches": [
			{
				"cx": 675.5,
				"cy": 216.5,
				"score": 0.381,
				"scale": 2.1,
				"mode": "color"
			},
			{
				"cx": 744.5,
				"cy": 218.5,
				"score": 0.355,
				"scale": 2.1,
				"mode": "color"
			}
		]
	},
	"bronchial-branches": {
		"x": 289,
		"y": 77,
		"width": 413,
		"height": 234,
		"pixelCount": 769,
		"components": 3,
		"tier": 3,
		"cx": 414.6,
		"cy": 225.3,
		"method": "opencv-template-match",
		"bestScore": 0.5567,
		"matches": [
			{
				"cx": 304.0,
				"cy": 295.0,
				"score": 0.557,
				"scale": 0.55,
				"mode": "gray"
			},
			{
				"cx": 690.5,
				"cy": 248.5,
				"score": 0.512,
				"scale": 0.45,
				"mode": "gray"
			},
			{
				"cx": 300.5,
				"cy": 90.5,
				"score": 0.51,
				"scale": 0.45,
				"mode": "gray"
			}
		]
	},
	"alveolar-fields": {
		"x": 138,
		"y": 803,
		"width": 30,
		"height": 33,
		"pixelCount": 509,
		"components": 1,
		"tier": 3,
		"cx": 153.2,
		"cy": 822.9,
		"method": "opencv-template-match",
		"bestScore": 0.4267,
		"matches": [
			{
				"cx": 153.0,
				"cy": 819.5,
				"score": 0.427,
				"scale": 0.59,
				"mode": "gray"
			}
		]
	},
	"airway-immune-compartment": {
		"x": 0,
		"y": 0,
		"width": 0,
		"height": 0,
		"pixelCount": 0,
		"components": 0,
		"tier": 0,
		"skipped": true,
		"method": "template-match-skip"
	},
	"airway-lumen": {
		"x": 0,
		"y": 0,
		"width": 0,
		"height": 0,
		"pixelCount": 0,
		"components": 0,
		"tier": 0,
		"skipped": true,
		"method": "template-match-skip"
	},
	"copd-inflammatory-structures": {
		"x": 0,
		"y": 0,
		"width": 0,
		"height": 0,
		"pixelCount": 0,
		"components": 0,
		"tier": 0,
		"skipped": true,
		"method": "template-match-skip"
	}
} as const;

export type LungHealthLayerBBox = (typeof lungHealthLayerBBoxes)[keyof typeof lungHealthLayerBBoxes];
